### ISSUE TITLE
Design the front-end side of the app

### ISSUE THREAD

**Issue by tsarchghs** [gjergjk71/toDo-Flask#1]
For now it's only HTML

**Comment by fernandezk26** [comment]
Any requirements or info? I'd be willing to help out with this

**Comment by gjergjk71** [comment]
@fernandezk26 Nope, I'll leave the design's *feel/look* choices to you since I'm no good in front-end.

**Comment by AyahRamahi** [comment]
Hi , I am a beginner. How can I help ?

**Comment by gjergjk71** [comment]
@AyahRamahi you can design the app, the html files are in templates folder

**Comment by gjergjk71** [comment]
Pull: #3
