### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AyahRamahi** [gjergjk71/toDo-Flask#2]
I forked the repo and tried to run it but got error that says 

"raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.
Set the secret_key on the application to something unique and secret.". 

Can anyone help ?

**Comment by gjergjk71** [comment]
You need to set a secret key to the app instance, like 
app.secret_key = os.urandom(12)

**Comment by AyahRamahi** [comment]
@gjergjk71 , it's working now. Thank you.
